#server.port=9999
server:
  port: 9090

# 数据库连接 RUL 
#spring.datasource.url=jdbc:oracle:thin:@localhost:1521/xe
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/xe
    driver-class-name: oracle.jdbc.OracleDriver
    username: location
    password: 123456
  thymeleaf:
    cache: false
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin
    packages:
      trust-all: true
  mail:
    host: smtp.qq.com
    port: 465
    username: 392977758@qq.com 
    password: afuefhophffwbjgd
    default-encoding: utf-8
    properties: 
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
        debug: true

      
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 0
    lettuce:
      pool:
        max-active: 80
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    
  cache:
    cache-names:
    - c1
    - c2
    - c3
    redis:
      time-to-live: 1800s # 缓存对象的生命周期
      
  session:
    store-type: redis # session数据存储到 redis.
  
mybatis:
  configuration:
    cache-enabled: true   # 默认是开启二级缓存全局配置的。


    
 
      


# 输出 SQL 语句 
#logging.level.com.wangrui.location.mapper=debug 
logging:
  level: 
    com.wangrui.location.mapper: debug
    
   

#mybatis.configuration.cache-enabled=true
